package frameworksdrivers.Gateways;

import usecases.CourseEnrollmentUseCase.EnrolmentCourseDataAccess;
import usecases.CourseEvaluatorUseCase.CourseDataAccess;
import usecases.CreateStudentUsecase.CreateStudentCourseDataAccess;

public interface CourseGateway extends EnrolmentCourseDataAccess, CreateStudentCourseDataAccess, CourseDataAccess {
}
