package frameworksdrivers.Gateways;

import usecases.CourseEnrollmentUseCase.EnrolmentSessionDataAccess;
import usecases.CourseEvaluatorUseCase.EvaluatorSessionDataAccess;
import usecases.LoginStudentUseCase.LoginSessionDataAccess;
import usecases.RunCourseUseCase.RunCourseSessionDataAccess;

public interface SessionGateway extends LoginSessionDataAccess, EnrolmentSessionDataAccess, RunCourseSessionDataAccess, EvaluatorSessionDataAccess {
}
