package frameworksdrivers;

import usecases.CourseEnrollmentUseCase.EnrolmentCourseDataAccess;
import usecases.CourseEvaluator.CourseDataAccess;
import usecases.CreateStudentUsecase.CreateStudentCourseDataAccess;

public interface CourseGateway extends EnrolmentCourseDataAccess, CreateStudentCourseDataAccess, CourseDataAccess {
}
